"""create_tables

Revision ID: 858fff4733d7
Revises: c8f88594948b
Create Date: 2026-01-13 16:55:30.124541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858fff4733d7'
down_revision: Union[str, Sequence[str], None] = 'c8f88594948b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_usd',
    sa.Column('date_time', sa.DateTime(), nullable=False, serever_default=sa.text('now()')),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_table('eth_usd',
    sa.Column('date_time', sa.DateTime(), nullable=False, serever_default=sa.text('now()')),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eth_usd')
    op.drop_table('btc_usd')
    # ### end Alembic commands ###
