"""init

Revision ID: e43c8ac476aa
Revises: 
Create Date: 2026-01-14 16:33:29.053548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43c8ac476aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_usd',
    sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_table('eth_usd',
    sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eth_usd')
    op.drop_table('btc_usd')
    # ### end Alembic commands ###
